name: 'Close Stale Issues'

on:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - name: 🗑 Close Stale Issues
        uses: actions/stale@v8
        with:
          days-before-close: 7
          days-before-stale: 30
          enable-statistics: true
          only-labels: 'status:needs more information'
          stale-issue-label: 'status:stale'
          stale-pr-label: 'status:stale'
          stale-issue-message: 'Hello 👋, this issue has been open for more than a month without a repro or any activity. If the issue is still present in the latest version, please provide a repro or leave a comment within 7 days to keep it open, otherwise it will be closed automatically. If you found a solution or workaround for the issue, please comment here for others to find. If this issue is critical for you, please consider sending a pull request to fix it.'
          stale-pr-message: 'Hello 👋, this pull request has been open for more than a month with no activity on it. If you think this is still necessary with the latest version, please comment and ping a maintainer to get this reviewed, otherwise it will be closed automatically in 7 days.'
